version: "3"

services:
 nkedge:
  container_name: nk_edge
  image: 192.168.0.70:5000/ai-edge/30xx:1.0.7.1
  network_mode: host
  restart: always
  runtime: nvidia
  volumes:
   - /home/nextk/Desktop/nk-edge/configs:/home/ai_edge/configs
   - /home/nextk/Desktop/nk-edge/license:/home/ai_edge/license
